export { default as Header } from './Header/Header'
export { default as Nav } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as TitleCard } from './TitleCard/TitleCard'
export { default as CommonCard } from './CommonCard/CommonCard'
export { default as Posts } from './Posts/Posts'
export { default as ResultBar } from './ResultBar/ResultBar'